<?php
require_once 'config/database.php';
require_once 'config/session.php';

requireLogin();

// Check if report data exists in session
if (!isset($_SESSION['report_data']) || !isset($_SESSION['report_type'])) {
    header('Location: reports.php');
    exit();
}

$data = $_SESSION['report_data'];
$reportType = $_SESSION['report_type'];
$filename = $_SESSION['report_filename'];

// Clear session data
unset($_SESSION['report_data']);
unset($_SESSION['report_type']);
unset($_SESSION['report_filename']);

// Simple HTML to PDF conversion (you can use libraries like TCPDF or FPDF for better results)
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo ucfirst(str_replace('_', ' ', $reportType)); ?> Report</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #667eea;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #667eea;
            margin: 0;
        }
        .header p {
            color: #666;
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #667eea;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        .btn {
            padding: 10px 20px;
            margin: 5px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            font-weight: bold;
            text-decoration: none;
            display: inline-block;
            transition: all 0.3s ease;
        }
        .btn-primary {
            background-color: #667eea;
            color: white;
        }
        .btn-primary:hover {
            background-color: #5a67d8;
            transform: translateY(-2px);
        }
        .btn-secondary {
            background-color: #6c757d;
            color: white;
        }
        .btn-secondary:hover {
            background-color: #5a6268;
            transform: translateY(-2px);
        }
        .btn-success {
            background-color: #28a745;
            color: white;
        }
        .btn-success:hover {
            background-color: #218838;
            transform: translateY(-2px);
        }
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1><?php echo ucfirst(str_replace('_', ' ', $reportType)); ?> Report</h1>
        <p>Generated on: <?php echo date('F j, Y \a\t g:i A'); ?></p>
        <p>Generated by: <?php echo htmlspecialchars($_SESSION['full_name']); ?></p>
    </div>

    <?php if (!empty($data)): ?>
        <table>
            <thead>
                <tr>
                    <?php foreach (array_keys($data[0]) as $header): ?>
                        <th><?php echo ucfirst(str_replace('_', ' ', $header)); ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $row): ?>
                    <tr>
                        <?php foreach ($row as $value): ?>
                            <td><?php echo htmlspecialchars($value ?: '-'); ?></td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p>No data available for this report.</p>
    <?php endif; ?>

    <div class="footer">
        <p>IT Asset Management System - Report generated on <?php echo date('Y-m-d H:i:s'); ?></p>
    </div>

    <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" class="btn btn-primary">
            <i class="fas fa-print"></i> Print Report
        </button>
        <button onclick="saveAsPDF()" class="btn btn-success">
            <i class="fas fa-save"></i> Save as PDF
        </button>
        <button onclick="goBack()" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Return to Reports
        </button>
    </div>

    <script>
        // Auto-print when page loads
        window.onload = function() {
            setTimeout(function() {
                window.print();
            }, 1000);
        }

        // Function to go back to reports page
        function goBack() {
            // Show loading state
            const button = event.target;
            const originalText = button.innerHTML;
            button.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Returning...';
            button.disabled = true;
            
            // Try to close the window first (works if opened in popup)
            if (window.opener) {
                window.close();
            } else {
                // If not opened in popup, redirect to reports page
                setTimeout(function() {
                    window.location.href = 'reports.php';
                }, 500);
            }
        }

        // Handle browser back button
        window.addEventListener('popstate', function(event) {
            window.location.href = 'reports.php';
        });

        // Add keyboard shortcut for closing (Ctrl+W or Escape)
        document.addEventListener('keydown', function(event) {
            if (event.key === 'Escape') {
                goBack();
            }
        });

        // Function to save as PDF (using browser's print to PDF feature)
        function saveAsPDF() {
            // Show loading state
            const button = event.target;
            const originalText = button.innerHTML;
            button.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';
            button.disabled = true;
            
            // Use browser's print dialog with PDF option
            setTimeout(function() {
                window.print();
                // Restore button after a delay
                setTimeout(function() {
                    button.innerHTML = originalText;
                    button.disabled = false;
                }, 2000);
            }, 500);
        }
    </script>
</body>
</html>
